[programs.localnet]
mpl_account_compression = "mcmt6YrQEMKw8Mw43FmpRLmf7BqRnFMKmAcbxE3xkAW"

[[test.genesis]]
address = "mnoopTCrg4p8ry25e4bcWA9XZjbNjMTfgYVGGEdRsf3"
program = "./target/deploy/wrapper.so"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
